version: '3'

# Needs environment variables set: PHP_PORT, PASSWORD
# Nv7haven needs PORT env var too

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: nv7haven
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  pg:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: nv7haven
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=pg_stat_statements",
        "-c",
        "pg_stat_statements.track=all",
        "-c",
        "pg_stat_statements.max=10000",
        "-c",
        "track_io_timing=on"
      ]
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgbackup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - pg
    depends_on:
      - pg
    user: postgres:postgres
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_DB=eod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PASSWORD}
      - SCHEDULE=@daily

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN="hydra"
    depends_on:
      - db
      - pg
    ports:
      - "${PHP_PORT}:8080"

  backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    volumes:
      - ./backups:/backup
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: ${PASSWORD}
      CRON_TIME: 0 3 * * *
      INIT_BACKUP: 1
      GZIP_LEVEL: 9
      MAX_BACKUPS: 30
    restart: unless-stopped

  filebackup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backups:/backups
      - ./data:/data

volumes:
  db-data:
  pg-data:
