version: '3'

# Needs environment variables set: PHP_PORT, PASSWORD
# Nv7haven needs PORT env var too

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: nv7haven
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
  
  pg:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: nv7haven
    ports:
      - "5432:5432"
    volumes: 
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
      - pg
    ports:
      - "${PHP_PORT}:8080"
  
  backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - db
    volumes:
      - ./backups:/backup
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: ${PASSWORD}
      CRON_TIME: 0 3 * * *
      INIT_BACKUP: 1
      GZIP_LEVEL: 9
      MAX_BACKUPS: 30
    restart: unless-stopped

  filebackup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backups:/backups
      - ./data:/data

volumes:
  db-data:
  pg-data:
